### ISSUE TITLE
@naverpay/eslint-config 패키지를 추가합니다

### ISSUE THREAD

**Issue by geonmo-nine** [NaverPayDev/code-style#11]

**Comment by 2-one-week** [comment]
@geonmo-nine (cc. @yceffort-naver) 님

eslint verion 9.x 이상에서는 config 이름 규칙이 `.eslintrc`에서 `eslint.config.js` 로 바뀐 것 같은데, 어떻게 처리할까요?? breaking change가 있는 것 같습니다

3일전 release 되었네용... https://github.com/eslint/eslint/releases/tag/v9.0.0

https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files

**Comment by yceffort-naver** [comment]
@geonmo-nine 님, 완료되셨으면 클로즈 부탁드립니다!

**Comment by geonmo-nine** [comment]
배포 완료로 이슈종료합니다!
