### ISSUE TITLE
plugin에 minimatch 의존성 추가

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/code-style#42]
https://github.com/NaverPayDev/code-style/blob/7b0a02eaec5bc5abedf036bde9de5de2ca589fc2/packages/eslint-plugin/lib/rules/memo-react-components.js#L2

에 `minimatch`의존성이 있는데 `package.json`선언에 빠진것 같슴니다..

**Comment by byhhh2** [comment]
https://github.com/NaverPayDev/code-style/pull/40 요기서 해결하겠습니다
