### ISSUE TITLE
nextjs 13 peer dep 이슈

### ISSUE THREAD

**Issue by ttppggnnss** [NaverPayDev/code-style#45]
@byhhh2 @yceffort-naver
안녕하세요
nextjs 13 및 react 18 관련해서 아래와 같은 Peer deps 이슈가 있는 것 같습니다
확인 부탁드려도 될까요? 🙇‍♂️ 

![image](https://github.com/NaverPayDev/code-style/assets/46037493/05e8b050-4872-449d-8729-a04ea37ed3cc)

![image](https://github.com/NaverPayDev/code-style/assets/46037493/2f8fdc34-f809-4653-9ad6-84a7edee335b)

**Comment by yceffort-naver** [comment]
@byhhh2 @yceffort-naver

**Comment by byhhh2** [comment]
@ttppggnnss 님, @yceffort-naver 님! cna@13, cra@18 기준으로 확인해보았습니다~~

- eslint-plugin-import의 peer가 exact 버전(2.25.2)만 기록되어 있어서, 만약 사용처에 다른 버전이 설치되어 있다면 eslint-confg가 설치되지 않습니다.  
  - 2.25.2 버전만 기록되어 있는 이유는 eslint-plugin-import [2.27.0 버전부터 parent, sibling 정렬 문제가 있어 고정되었습니다. ㅜ](https://github.com/import-js/eslint-plugin-import/issues/2685)
  - 위 이슈는 eslint-plugin-import를 `dependencies`로 옮겨 수정하겠습니다.
- `@typescript-eslint/parser`과 `@typescript-eslint/eslint-plugin`는 동일한 major 버전을 가져야 하고, 6.9 버전 이상부터 호환되는 코드가 있어서 peer를 `>= 7`로 수정하려합니다. 만약 사용처에서 관련 peer dep 오류가 발생한다면 7 버전 이상으로 overrides가 필요할 것 같습니당

**Comment by yceffort-naver** [comment]
의존성과 eslint 전문가가 다 되셨군요 (...)
PR 주시면 검토해보겠습니다!!

**Comment by byhhh2** [comment]
@ttppggnnss 님! 

[코멘트](https://github.com/NaverPayDev/code-style/issues/45#issuecomment-2208249508) 내용 `@naverpay/eslint-config@1.0.5` 버전에 반영되었습니다 :)
