### ISSUE TITLE
editorconfig 및 markdown-lint 설치 관련 질문

### ISSUE THREAD

**Issue by ryuhangyeong** [NaverPayDev/code-style#55]
## 질문

- `editorconfig` 및 `markdown-lint` 의 `package.json` 에서 `postinstall` 가 실행되며 스크립트가 실행되는 것으로 확인됩니다. 스크립트가 실행되면서 기존 프로젝트에 각 설정 파일이 생길 것으로 예상했는데. 실제로 설정 파일이 생성되지 않습니다. 혹시 별도 명령어를 실행 해야 하는 것이 있을까요? 아니면 권한 문제일까요?

## 시도 해본 것

1. `npm install`
2. `npm install @naverpay/editorconfig -D`

## 환경

- window 11
- git bash

## 기타

- 좋은 라이브러리 공개해주셔서 감사합니다.

**Comment by 2-one-week** [comment]
안녕하세요 @ryuhangyeong 님

우선 저희 패키지에 관심 가져주셔서 감사드립니다!

markdown lint 의 [postinstall script](https://github.com/NaverPayDev/code-style/blob/main/packages/markdown-lint/package.json#L17) 인 `node postInstall/index.js` 실행이 안되어,  [markdown lint config 파일인 `.markdownlint.jsonc`](https://github.com/NaverPayDev/code-style/blob/main/.markdownlint.jsonc) 가 생성되지 않았단 말씀이실까요??

(cc. @yceffort-naver  @byhhh2 )

**Comment by ryuhangyeong** [comment]
@2-one-week 

네 맞습니다. 일단 `npm install @naverpay/editorconfig -D` 명령어로 **설치시 설정 파일이 사용자 프로젝트에 생성되는게 의도하신게 맞을까요?**

그게 맞다면 설치를 해도 설정 파일이 생성되지 않는게 맞습니다.

```
# 예시 폴더
cd node-example
```

```
npm install @naverpay/editorconfig -D
```

혹, 제가 이해하지 못해서 잘못 테스트하고 있는걸 수도 있으니 상세히 알려주시면 다시 해보겠습니다.

**Comment by yceffort-naver** [comment]
@ryuhangyeong 님, 자동생성되어야 하는게 맞는데 안되고 있는 것 같습니다. 저희가 문제 파악해보겠습니다. 
@byhhh2 님, 확인 부탁드립니다.

참고로 https://github.com/NaverPayDev/code-style/blob/main/packages/markdown-lint/.markdownlint.jsonc 를 수동생성해주시면 사용하실수 있으니 참고 부탁드립니다.

감사합니다 :)

**Comment by 2-one-week** [comment]
@ryuhangyeong 님

제 컴퓨터 (m1 mac) 에서 확인해본 결과, 설치가 제대로 되고 있는데요.

`postinstall` 이 node로 script를 실행하여 파일을 생성하고 있는 로직인데, 혹시 컴퓨터에 깔려있는 node의 권한이 해당 폴더에 파일을 생성할 수 있는 권한이 있는지 확인 부탁드려도 될까요?

**Comment by ryuhangyeong** [comment]
@2-one-week 

테스트 중인 폴더에서 파일 생성 권한 확인을 위해 아래와 같은 스크립트 작성 후 테스트해보았을 때, 정상적으로 생성되는 것을 보아 파일 생성 권한은 있는 것으로 파악됩니다.

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/af41e381-c3df-4574-a6ec-070db9d865fa">

아래 명령어 둘다 실행해봐도 생성되지 않습니다. 제가 테스트 한게 맞을까요?

```
npm i
npm install @naverpay/editorconfig -D
```

크리티컬한 문제는 아니라 평일 업무 시간에 봐주셔도 됩니다..!

**Comment by Dev-Taehui** [comment]
Windows에서 확인해보았으나 잘 생성되는 것을 확인하였습니다. 다만, 프로젝트가 git 기반이 아니라면 동작하지 않습니다.
아무 메시지도 없다면 이미 `.editorconfig` 파일이 존재하는 분기를 탄게 아닐까 생각됩니다.
관련 분기에 `console.log`를 추가하면 좋을 것 같습니다.

```js
console.log(".editorconfig already exists")
```

**Comment by 2-one-week** [comment]
@Dev-Taehui 님

> 다만, 프로젝트가 git 기반이 아니라면 동작하지 않습니다.

제가 윈도우를 잘 몰라서 그런데요! postinstall 과 같은 post- prefix는 npm의 기능이라 git에 영향을 받지 않을 것 같은데 아닐까요??

관련 문서 : https://docs.npmjs.com/cli/v10/using-npm/scripts#pre--post-scripts

**Comment by Dev-Taehui** [comment]
@2-one-week `postinstall` 같은 package.json의 Hook이 아닌 `createConfigFile.js`의 `const gitRoot = execSync('git rev-parse --show-toplevel').toString().trim()`을 보고 `git` 기반으로 판단하였습니다.

**Comment by 2-one-week** [comment]
@Dev-Taehui 님

아 그렇네요 확인 감사드립니다! 

git 기반인지도 확인이 필요하겠네요! (cc. @byhhh2 )

**Comment by ryuhangyeong** [comment]
@2-one-week @Dev-Taehui 🙇

신경 써주셔서 감사합니다. 테스트를 위해 비어있는 프로젝트에서 테스트했어서 안된다고 생각했던 모양입니다.

`.git` 파일이 존재하는 기존 프로젝트에서 설치하니 정상적으로 생성되는 것 확인되었습니다!

**Comment by ryuhangyeong** [comment]
해당 이슈 닫아도 될까요?

**Comment by yceffort-naver** [comment]
넵 감사합니다! 관심 가져주셔서 감사합니다 😀 
앞으로도 많은 관심 부탁드립니디. 🙇
