### ISSUE TITLE
[eslint-plugin] 신규 플러그인 / 룰 검토

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/code-style#58]
### O

- [x] eslint-config-standard 제거
  - neostandards 로 대체
- [x] eslint-plugin-yml 
  - 현재 yaml은 prettier 에 위임하고 있지만,
  - fomatting -> prettier, 외에 룰 도입

#### strict config 추가

- [x] [eslint-plugin-sonarjs](https://github.com/SonarSource/SonarJS/blob/master/packages/jsts/src/rules/README.md) 보류
  - 신규 프로젝트에는 괜찮을듯하지만, 기존 프로젝트에는 파급력이 커보임
  - `eslint-plugin-unicorn`랑 충돌나는 옵션 고려 필요
- [x] [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn) 보류
  - 위와 동일한 이유

---

### X

- [x] eslint-plugin-node 대신 eslint-plugin-n 으로 (업데이트가 느려터짐)
  - eslint-plugin-node 제거 됌
- [x] [eslint-plugin-workspaces](https://github.com/joshuajaco/eslint-plugin-workspaces) 보류
  - 현재 코드에 변경사항이 크지 않다면 적용해볼만함
  - 워크스페이스 아닌 환경 고려
- [x] eslint-plugin-compat 보류
  - 플러그인은 맘에 들지만 browserlist 기반으로 동작해, 사용하는 쪽에서 별도의 설정이 필요하다는 내용을 명시해줘야함
- [ ] [eslint-plugin-vitest](https://github.com/vitest-dev/eslint-plugin-vitest) 보류
    제공자 입장에서 대상 파일을 선언하는 방식은 지양하기 위해 보류
    ```js
    export default [
        js.configs.recommended,
        {
            files: ['**/__tests__/**', '**/tests/**', '**/*{.,_}{test,spec}.{js,cjs,mjs,jsx,ts,cts,mts,tsx}'],
            ...vitest.configs.recommended,
        },
    ]
    ```
- [x] [eslint-plugin-css-modules](https://github.com/atfzl/eslint-plugin-css-modules)
  - Project status: NOT MAINTAINED
- [x] [eslint-plugin-deprecation](https://github.com/gund/eslint-plugin-deprecation)
-> deprecated // https://typescript-eslint.io/rules/no-deprecated
n/no-deprecated-api 가 역할을 하고 있는 것으로 보임

**Comment by yceffort-naver** [comment]
@NaverPayDev/frontend 혹시 이외에 평소에 쓰고 싶으셨던 룰/플러그인 있으시면 공유 부탁드립니다~

**Comment by yongholeeme** [comment]
@byhhh2 님, 저 질문있습니다. eslint-config 에서 테스트 코드 작성했던 기준은 어떤건지 기억하시나요? https://github.com/NaverPayDev/code-style/tree/main/packages/eslint-config/tests

**Comment by byhhh2** [comment]
@yongholeeme 님~ 
config를 extends 한 rule 빼고 다 작성했어요! (아마도)

**Comment by yongholeeme** [comment]
아하, 이해했습니다~~ 참고하겠습니다

**Comment by yceffort-naver** [comment]
룡호님

https://github.com/sindresorhus/eslint-plugin-unicorn

이것도한번..!

**Comment by yongholeeme** [comment]
@yceffort-naver 님, 좀 파격적인 플러그인인데요ㅋㅋ 
- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md 
- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md
- https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-lonely-if.md
- ...

**Comment by yceffort-naver** [comment]
몇개만.. 할까요..? 이거 싸다구 맞으려나? ㅋㅋㅋ
사실 제가 완전 실무자도 아닌데 하자고 하기 좀 거시기하기도하네요...

**Comment by 2-one-week** [comment]
> https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-for-each.md

찬성!

갠적으로 중간에 break 못하는 forEach 보단 for-of 선호 ㅎㅎ

> https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-reduce.md
> https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-lonely-if.md

reduce랑 if는 좀ㅋㅋ

**Comment by yceffort-naver** [comment]
(내용은 얼추 다 동의하는데..)

**Comment by yceffort-naver** [comment]
https://github.com/vitest-dev/eslint-plugin-vitest

**Comment by yujeong-jeon** [comment]
혹시 https://typescript-eslint.io/rules/consistent-type-imports/ 로 `import type` 강제할 수도 있을까요?

**Comment by yceffort-naver** [comment]
마자 이거 나 뭐까먹었나 헀네 이거이거 저도 하고 싶어요

**Comment by yujeong-jeon** [comment]
https://www.npmjs.com/package/eslint-plugin-unused-imports
이 룰도 auto fix 되게 하면 어떨까요~? 일일이 제거 힘들..

**Comment by yongholeeme** [comment]
> 혹시 https://typescript-eslint.io/rules/consistent-type-imports/ 로 import type 강제할 수도 있을까요?

저도 좋습니다만, 이 설정 키려면 vscode의 [`typescript.preferences.includePackageJsonAutoImports`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/#settings-to-prefer-type-auto-imports) 도 같이 켜주는 게 좋을 것 같네요. cc https://github.com/NaverPayDev/code-style/tree/main/packages/eslint-config#vscode

**Comment by yujeong-jeon** [comment]
> 저도 좋습니다만, 이 설정 키려면 vscode의 [typescript.preferences.preferTypeOnlyAutoImports ](https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/#settings-to-prefer-type-auto-imports) 도 같이 켜주는 게 좋을 것 같네요.
 
어 저는 지금 설정에서 켜지 않았는데 잘 되는거 같습니다..? (code-style 안쓰는 대출서비스 환경에서 테스트 함)
아마 별개가 아닐까 싶은데 일관되려면 켜는게 잘 어울릴거 같긴합니다 :)

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#settings-to-prefer-type-auto-imports

**Comment by yongholeeme** [comment]
> 어 저는 지금 설정에서 켜지 않았는데 잘 되는거 같습니다..?

@yujeong-jeon 님, 설명이 부족했네요. `preferTypeOnlyAutoImports` 안키면 auto import 할 때, import 으로 자동완성되지 않나요?

**Comment by yceffort-naver** [comment]
## 제안

- jest 지원 날리기: 이제 vitest 로 갈 때가 되었고, jest 는 죽은지 좀 됐음 (보일러플레이트가 너무 많음)
- node에 있는 unused_Vars를 warn 에서 error로: 냉무...! (`_`만 지원)

**Comment by 2-one-week** [comment]
https://github.com/jestjs/jest/releases

v30으로 바로 가려나본데여?

**Comment by yceffort-naver** [comment]
vitest 쓰는 경우도 있어서, 이제 jest 를 굳이 기본값에 넣을 필요는 없을 것 같습니다!

> https://engineering.fb.com/2022/05/11/open-source/jest-openjs-foundation/ 도망간줄알았는데 그래도 아직 명맥을 이어가고는 있군요
